# Importing the required libraries

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [10]:
df = pd.read_csv('heart.csv')

In [11]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [12]:
df.shape

(918, 12)

In [13]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [15]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

# Putting Feature Variable to X and Target variable to y.

In [18]:
print(df.columns)

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [19]:
# Putting feature variable to X
X = df.drop('HeartDisease',axis=1)
# Putting response variable to y
y = df['HeartDisease']

# Train-Test-Split is performed

In [20]:
# now lets split the data into train and test
from sklearn.model_selection import train_test_split
# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((642, 11), (276, 11))

# Let’s import RandomForestClassifier and fit the data.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)
#%%time
classifier_rf.fit(X_train, y_train)

ValueError: could not convert string to float: 'M'

In [ ]:
# checking the oob score
classifier_rf.oob_score_

0.656084656084656

## Let’s do hyperparameter tuning for Random Forest using GridSearchCV and fit the data.

In [ ]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)
params = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}
from sklearn.model_selection import GridSearchCV
# Instantiate the grid search model
grid_search = GridSearchCV(estimator=rf,
                           param_grid=params,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")
#%%time
grid_search.fit(X_train, y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [ ]:
grid_search.best_score_

0.6985815602836879

In [ ]:
rf_best = grid_search.best_estimator_
rf_best

RandomForestClassifier(max_depth=5, min_samples_leaf=10, n_estimators=10,
                       n_jobs=-1, random_state=42)

## Now, let’s visualize

In [ ]:
from sklearn.tree import plot_tree
plt.figure(figsize=(80,40))
plot_tree(rf_best.estimators_[5], feature_names = X.columns,class_names=['Disease', "No Disease"],filled=True);

InvalidParameterError: The 'feature_names' parameter of plot_tree must be an instance of 'list' or None. Got Index(['age', 'sex', 'BP', 'cholestrol'], dtype='object') instead.

In [ ]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in d:\anaconda\lib\site-packages (1.3.0)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/79/3d/02d5d3ed359498fec3abdf65407d3c07e3b8765af17464969055aaec5171/scikit_learn-1.4.2-cp311-cp311-win_amd64.whl.metadata
  Downloading scikit_learn-1.4.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.19.5 in d:\anaconda\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.6.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\lib\site-packages (from scikit-learn) (2.2.0)
Downloading scikit_learn-1.4.2-cp311-cp311-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 1.4 MB/s eta 0:00:08
    --------------------------------------- 0.2/10.6 MB 1.8 MB/s eta 0:00:06
   - -------------------------------------- 0.5/10.6 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/10.6 MB 5.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/10.6 MB 6.2 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/10.6 MB 6.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/10.6 MB 7.6 MB/s eta 0:00:02
   ----------- ---------------------------- 3.0/10.6 MB 8.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.5/10.6 MB 8.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.1/10.6 MB 9.1 MB/s eta 0:00:01
   --------------- ------------------------ 4.2/10.6 MB 9.0 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.6 MB 8.3 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.6 MB 8.3 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 5.0/10.6 MB 5.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.6/10.6 MB 6.0 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ------------------------ --------------- 6.5/10.6 MB 5.1 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.5/10.6 MB 4.7 MB/s eta 0:00:01
   ------------------------------ --------- 8.0/10.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------- -------- 8.2/10.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.5/10.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.6 MB 4.8 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------- ----- 9.1/10.6 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.6 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 4.2 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.0
    Uninstalling scikit-learn-1.3.0:
      Successfully uninstalled scikit-learn-1.3.0

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\anaconda\\Lib\\site-packages\\~klearn\\cluster\\_dbscan_inner.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [ ]:
from sklearn.tree import plot_tree
plt.figure(figsize=(80,40))
plot_tree(rf_best.estimators_[7], feature_names = X.columns,class_names=['Disease', "No Disease"],filled=True);

InvalidParameterError: The 'feature_names' parameter of plot_tree must be an instance of 'list' or None. Got Index(['age', 'sex', 'BP', 'cholestrol'], dtype='object') instead.

### The trees created by estimators_[5] and estimators_[7] are different. Thus we can say that each tree is independent of the other.

### Now let’s sort the data with the help of feature importance

In [ ]:
rf_best.feature_importances_

array([0.46128487, 0.2180848 , 0.13174619, 0.18888413])

In [ ]:
## feature importance

imp_df = pd.DataFrame({
    "Varname": X_train.columns,
    "Imp": rf_best.feature_importances_
})

In [ ]:
imp_df.sort_values(by="Imp", ascending=False)

      Varname       Imp
0         age  0.461285
1         sex  0.218085
3  cholestrol  0.188884
2          BP  0.131746